[terminal.shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["--", "cd $HOME && tmux attach || tmux"]

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 12.0

[scrolling]
history = 100000
multiplier = 3

[window]
opacity = 0.8
startup_mode = "Maximized"
dynamic_title = false
